server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost/rollin?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  devtools:
    livereload:
      enabled: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLInnoDBDialect
#        format_sql: 'true'
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      ddl-auto: update
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: 'true'
#jwt:
#  secret_key: SECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEY
#  expTime : 86400000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health, beans, httpstrace
