server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.0.42:3306/rollin?serverTimezone=UTC&characterEncoding=UTF-8
    username: rolin
    password: dbsdn123123!

  devtools:
    livereload:
      enabled: true
